### PR TITLE
Fix video texture memory leak

### PR DESCRIPTION
**Pull request by Tobias-Fischer**

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Hi @traversaro, can you please merge and forward merge into `devel`?
Thanks, Tobi

**Comment by traversaro** [comment]
Thanks a lot!

**Comment by Tobias-Fischer** [comment]
Thanks for merging!

**Comment by randaz81** [comment]
I don't think that the implementation of this plugin is complete yet...

**Pull request merged**
