### PR TITLE
Fix wrong install include for gazebo_yarp_lib_common library

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/gazebo-yarp-plugins/issues/643

### CODE REVIEW

**Review by HosameldinMohamed — APPROVED** [review]
Thanks! I tested the installed library and the problem no longer exists!

I was searching for `INTERFACE_INCLUDE_DIRECTORIES` in the source code but couldn't find it!

**Comment by HosameldinMohamed** [comment]
You may want to update the CHANGELOG too

**Comment by traversaro** [comment]
> Thanks! I tested the installed library and the problem no longer exists!
> 
> I was searching for `INTERFACE_INCLUDE_DIRECTORIES` in the source code but couldn't find it!

That property is probably defined in the `GazeboYARPPluginsTargets.cmake` file that is generated and installed by CMake. That property is defined indirectly in the code via the `target_include_directories(gazebo_yarp_lib_common INTERFACE $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)` calls.

**Comment by HosameldinMohamed** [comment]
> > Thanks! I tested the installed library and the problem no longer exists!
> > I was searching for `INTERFACE_INCLUDE_DIRECTORIES` in the source code but couldn't find it!
> 
> That property is probably defined in the `GazeboYARPPluginsTargets.cmake` file that is generated and installed by CMake. That property is defined indirectly in the code via the `target_include_directories(gazebo_yarp_lib_common INTERFACE $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)` calls.

Great! Thanks!

**Pull request merged**
