### PR TITLE
Catch them all headers cleanup

### PR DESCRIPTION
**Pull request by Yeshasvitvs**
See https://github.com/robotology/gazebo-yarp-plugins/issues/221
headers cleaned up from the all the plugins modules
@traversaro please check if this helps to reduce the compilation time

### CODE REVIEW

**Comment by traversaro** [comment]
This is great! I think this should reduce the compilation time, but even if this is not the case we should merge it anyway because it helps in cleaning the code. Thanks a lot @Yeshasvitvs !

**Comment by Yeshasvitvs** [comment]
welcome @traversaro
if you also have someother ideas to reduce the compile time we can look into that

**Comment by barbalberto** [comment]
:+1: 
What is taking a huge amount of compilation time is having all the warning check enabled.
We can reduce them to a reasonable check and enable all checks in the build farm or somewhere else.

**Comment by francesco-romano** [comment]
I am not able to test this PR on macOS as I don't have gazebo installed anymore. Maybe @traversaro can do it?

@barbalberto i am completely against disabling warnings checks.

**Comment by traversaro** [comment]
I think we can move the discussion on how to further speed-up the compilation process in https://github.com/robotology/gazebo-yarp-plugins/issues/221 . @Yeshasvitvs thanks for the PR, merging!

**Pull request merged**
