### PR TITLE
laser sensors plugins refactored

### PR DESCRIPTION
**Pull request by randaz81**
* laserSensorDriver now derives from Lidar2DDeviceBase
* DoubleLaser is now able to parse [SENSOR] and [SKIP] sections

requires robotology/yarp#2205

### CODE REVIEW

**Comment by traversaro** [comment]
This requires to merge https://github.com/robotology/yarp/pull/2205/files before?

**Comment by randaz81** [comment]
succesfully tested

**Comment by traversaro** [comment]
Hi @randaz81 , if this PR requires the change in YARP contained in https://github.com/robotology/yarp/pull/2205, is there any plan for when the next feature release of YARP will be release, including this change? 

We were planning to have the next feature release of gazebo-yarp-plugins on August 2020, and if the next feature release of  YARP is planned to be later, this dependency of gazebo-yarp-plugins `devel` on YARP master could be complicating that plan.

**Comment by pattacini** [comment]
This is quite an important point. Can we solve this asap, please?

**Comment by pattacini** [comment]
@randaz81 please don't delete comments 😉

**Pull request merged**
