### PR TITLE
Add exported targets for gazebo_yarp_lib_common and gazebo_yarp_singleton

### PR DESCRIPTION
**Pull request by traversaro**
See `doc/use_as_library.md` for usage. 

cc @barbalberto @valegagge

### CODE REVIEW

**Comment by traversaro** [comment]
Travis test are invalid due to the outdated docker images, but feel free to review, thanks.

**Comment by diegoferigo** [comment]
This is a nice feature. Do you have any use case in mind?

I'm on the docker images (again). Hopefully the situation will calm down now after the yarp 3 release.

**Comment by barbalberto** [comment]
@diegoferigo the use case is the gazebo plugin for the R1 tripod structure.
You can find it here: https://github.com/robotology/cer

**Comment by traversaro** [comment]
It is to remove this monstrosity : https://github.com/robotology/cer/blob/master/cmake/FindGazeboYarpPlugins.cmake .
For more info check https://github.com/robotology/cer/issues/84 .

**Pull request merged**
