### PR TITLE
yarp::dev::IRgbVisualParams in multicamera and depthCamera

### PR DESCRIPTION
**Pull request by drdanz**
Unfortunately, at the moment, in YARP we don't have an interface for a multicamera. This means that, if the camera parameters are different, this will work properly only for the first camera.

Depends on #560

### CODE REVIEW

**Comment by traversaro** [comment]
Just to clarify, the source of this code is the existing code in `gazebo_yarp_depthcamera`, right? Not sure if you want to fix the `retificationMatrix` typo after https://github.com/robotology/yarp/pull/2593 ?

**Comment by traversaro** [comment]
Can you update the CHANGELOG?

**Comment by traversaro** [comment]
To fix the CI, you may want to rebase over latest devel to get https://github.com/robotology/gazebo-yarp-plugins/pull/557 .

**Comment by drdanz** [comment]
> Just to clarify, the source of this code is the existing code in gazebo_yarp_depthcamera, right? Not sure if you want to fix the retificationMatrix typo after robotology/yarp#2593 ?

Yes, I was saving it for the next PR, where I was fixing this, and the depthcamera, and also fixing getRgbIntrinsicParam when the distortion is not set, but perhaps it is better to have it all in one PR, I'll update it...

**Comment by traversaro** [comment]
> 
> 
> > Just to clarify, the source of this code is the existing code in gazebo_yarp_depthcamera, right? Not sure if you want to fix the retificationMatrix typo after [robotology/yarp#2593](https://github.com/robotology/yarp/pull/2593) ?
> 
> Yes, I was saving it for the next PR, where I was fixing this, and the depthcamera, and also fixing getRgbIntrinsicParam when the distortion is not set, but perhaps it is better to have it all in one PR, I'll update it...

Ok, let's leave it for the next PR then!

**Comment by drdanz** [comment]
> Ok, let's leave it for the next PR then!

Too late, just updated the PR 😆

**Comment by drdanz** [comment]
Should this be `master` for gazebo-yarp-plugin` `devel` branch?
https://github.com/robotology/gazebo-yarp-plugins/blob/90df1566fc05e5830252bbfc1d34df4b7a4ca976/.github/workflows/ci.yml#L31

**Comment by drdanz** [comment]
Rebased over #560 in order to build with YARP master

**Comment by drdanz** [comment]
@traversaro: All checks have passed. Can we merge this, so that I can rebase #559?

**Review by traversaro — APPROVED** [review]

**Comment by drdanz** [comment]
Thanks @traversaro

**Pull request merged**
