### PR TITLE
updated correct timestamp GazeboYarpLaserSensorDriver

### PR DESCRIPTION
**Pull request by ste93**
since Lidar2DDeviceBase has a timestamp inside and lasersensor inherits from it, I would suggest use the timestamp from taht class. It has also an api getLastInputStamp ()  to get that stamp.

### CODE REVIEW

**Comment by ste93** [comment]
@randaz81

**Review by randaz81 — APPROVED** [review]
thank you, this was an important bugfix

**Comment by randaz81** [comment]
Additionally, since yarp 3.6 has been released, I think that we can safely remove the dependency from `IPreceiselyTimed`
https://github.com/robotology/gazebo-yarp-plugins/pull/604/files#diff-a33e9fff4431518b3add5ded498eae3af09ef01c83956d6fc6abd0a70de405b8R67-R70

REASON: in general `IPreceiselyTimed interface should be avoided` as much as possible, and possibly `deprecated`. Timestamps must be obtained together with the data using a single call to a get method()**. Otherwise,  it cannot be guaranteed that the timestamp is really associated with the retrieved data. (Threads can be interrupted etc.)**

**Comment by traversaro** [comment]
Yes, feel free to remove the inheritance from `IPreceiselyTimed` and require YARP 3.6 as suggested by @randaz81 , thanks!

**Comment by ste93** [comment]
@randaz81 updated, for me it can be merged. FYI @traversaro

**Comment by traversaro** [comment]
> @randaz81 updated, for me it can be merged. FYI @traversaro

To require YARP 3.6 you need to modify the CMake in https://github.com/robotology/gazebo-yarp-plugins/blob/master/CMakeLists.txt#L49 . Could you also update the CHANGELOG?

**Comment by ste93** [comment]
related to https://github.com/robotology/gazebo-yarp-plugins/issues/598

**Comment by traversaro** [comment]
Thanks @ste93 .

**Comment by ste93** [comment]
thanks @traversaro

**Pull request merged**
