### PR TITLE
YARP 3 and Gazebo 9 cleanup 

### PR DESCRIPTION
**Pull request by traversaro**
* Remove usage of YARP_INCLUDE_DIRS CMake variable  : https://github.com/robotology/gazebo-yarp-plugins/commit/251ff24be775e15d380f8f11d924ff9a544b9baf 
* yarp::os::ConstString ---> std::string : https://github.com/robotology/gazebo-yarp-plugins/commit/8e09d7b9c2c65c43c55c981812f899509c91bf4a 
* Fix Gazebo 9 deprecation :  https://github.com/robotology/gazebo-yarp-plugins/commit/bb6ef7bf77bffeb876a980e4c061fd66d3a71137

### CODE REVIEW

**Comment by traversaro** [comment]
The docker images need to be updated.

**Comment by traversaro** [comment]
docker images generation currently failing due to the icub-tests , due to https://github.com/robotology/yarp/issues/1735 (pending fix in https://github.com/robotology/icub-tests/pull/41) and https://github.com/robotology/yarp/issues/1736 .

**Comment by traversaro** [comment]
Merging as the CI will be probably broken by something else.

**Comment by diegoferigo** [comment]
@traversaro Images are again misaligned after the Yarp 3.0 release. Need some time to sync. Will be fixed soon :wink:

**Comment by traversaro** [comment]
@diegoferigo yep, but  anyway https://github.com/robotology/yarp/issues/1736 is still present, so I think it make sense to move forward without CI for now.

**Pull request merged**
