### PR TITLE
[controlboard] Fix issue with ResetWorld

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/gazebo-yarp-plugins/issues/92 .

A callback for the resetWorld event was added.
During a World Reset, the state of the controller is reset to the initial state
(including control mode,  interaction mode and state of the trajectory generators)

@jeljaik @rlober 
Can you test it?

cc @DanielePucci

### CODE REVIEW

**Comment by traversaro** [comment]
During the night I realized that if you use the Gazebo WorldReset with the YARP clock synchronization, you have misbehaviour in the `delay` function : https://github.com/robotology/yarp/blob/31766f34f115fa77826dae3fc8e2686688fd7aef/src/libYARP_OS/src/NetworkClock.cpp#L128 .  
An easy approach is to return from all the `delay` functions as soon as the clock is reseted (i.e. the clock goes backward in time).

**Comment by barbalberto** [comment]
Does the `world reset`  also resets the clock?

**Comment by rlober** [comment]
@traversaro 
Thanks for the fix! I just tested it but I am still getting the HW faults:
```
[DEBUG]Initializing Trajectory Generator with default values 
[DEBUG]Initializing Trajectory Generator with current values 
[DEBUG]Initializing Trajectory Generator with current values 
[ERROR]An hardware fault occurred on joint  2  torque too big! (  -12238.3  ) 
[ERROR]An hardware fault occurred on joint  0  torque too big! (  -4589.72  ) 
[ERROR]An hardware fault occurred on joint  1  torque too big! (  3500.31  ) 
[ERROR]An hardware fault occurred on joint  3  torque too big! (  2054.79  ) 
[ERROR]An hardware fault occurred on joint  0  torque too big! (  -4589.94  ) 
[ERROR]An hardware fault occurred on joint  1  torque too big! (  3499.56  ) 
[ERROR]An hardware fault occurred on joint  3  torque too big! (  2054.82  ) 
[ERROR]An hardware fault occurred on joint  0  torque too big! (  -6201.11  ) 
[ERROR]An hardware fault occurred on joint  3  torque too big! (  -6197.34  ) 
[ERROR]An hardware fault occurred on joint  4  torque too big! (  6176.51  ) 
[ERROR]An hardware fault occurred on joint  0  torque too big! (  -6041.43  ) 
[ERROR]An hardware fault occurred on joint  3  torque too big! (  -6202.24  ) 
[ERROR]An hardware fault occurred on joint  4  torque too big! (  6338.67  ) 
[ERROR]An hardware fault occurred on joint  6  torque too big! (  2000.05  ) 
[ERROR]An hardware fault occurred on joint  6  torque too big! (  2000.05  ) 
[ERROR]An hardware fault occurred on joint  0  torque too big! (  -2000.36  ) 
[ERROR]An hardware fault occurred on joint  1  torque too big! (  2000.04  ) 
[ERROR]An hardware fault occurred on joint  2  torque too big! (  -2000.19  ) 
[ERROR]An hardware fault occurred on joint  2  torque too big! (  -2000.09  ) 
[ERROR]An hardware fault occurred on joint  1  torque too big! (  2000.16  ) 
```

I just opened `icub.world` and hit `ctrl+r`

**Comment by traversaro** [comment]
Which version of Gazebo are you using?

**Comment by rlober** [comment]
7.0.0

**Comment by jeljaik** [comment]
I tested on mine too, i.e.

OS X El Capitan
Gazebo 6.5.1

I get the same messages (although the robot does get back on its feet). Moreover if you start the `yarpmotorgui` even if you put those joints in `idle` and then run them again, they remain in `HW`.

**Comment by traversaro** [comment]
@barbalberto Yes, it resets also the time. 

@rlober @jeljaik For me it is working fine with Gazebo 7.2 (the latest version). Can you try with Gazebo 7.2 ? Otherwise I am really puzzled...

**Comment by traversaro** [comment]
Probably without this fix : https://bitbucket.org/osrf/gazebo/pull-requests/2255/reset-ode-joint-force-feedback-after-world/diff the world reset is still not working on ODE.

**Comment by jeljaik** [comment]
Right ... will update Gazebo then :)

**Comment by jeljaik** [comment]
Still on OS X El Capitan with Gazebo 7.2 I get the following error after I put the robot:

```bash
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[libprotobuf ERROR google/protobuf/descriptor_database.cc:57] File already exists in database: time.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1018] CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
```

**Comment by rlober** [comment]
@traversaro 

Ok so @ahoarau checked on 14.04 in Gazebo 7.2 and everything is working fine. I haven't updated in 16.04 yet but I am sure it will work. @jeljaik is checking on OSX but having some trouble getting 7.2 installed. 

I think you could go ahead and merge this as it doesn't seem to break anything and works for Gazebo >= 7.2.

**Comment by jeljaik** [comment]
No I got 7.2 installed correctly, the one thing missing is this thing with the robot when I put it in the world.

**Comment by traversaro** [comment]
> this thing with the robot when I put it in the world.
??

**Comment by jeljaik** [comment]
I meant, Gazebo crashes as soon as I put the robot, with the error message I wrote before.

**Comment by traversaro** [comment]
Ah sorry @jeljaik, I missed the message. I strongly suspect that it is a problem of not updated dependencies in homebrew or something like that. Have you tried to brew update protobuf (and related packages)?

**Comment by traversaro** [comment]
Anyhow, I think we can merge because the issue in itself is solved. In  https://github.com/robotology/gazebo-yarp-plugins/pull/247/commits/ff550da486fb31cb0cefc0332056e39f31c928c5 I documented that we recommend the use of the latest Gazebo to avoid problems.

**Comment by jeljaik** [comment]
Ok guys I had some issues when upgrading gazebo to 7.2 with wrongly linked libraries, etc. Everything's fine now :) `Reset world` is also working on OS X El Capitan with Gazebo 7.2. I guess you can close this issue.

**Pull request merged**
