### PR TITLE
Release gazebo-yarp-plugins v4.0.0

### PR DESCRIPTION
**Pull request by traversaro**

### CODE REVIEW

**Comment by traversaro** [comment]
Please ignore the CI failures, they will be fixed once a YARP 3.5 conda package is generated, hopefully at the beginning of next week.

**Review by GiulioRomualdi — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
Remember this
```
[WARNING] VELOCITY_CONTROL: 'velocityControlImplementationType' param missing.  Using the default value of 'direct_velocity_pid', but the parameter will be compulsory gazebo-yarp-plugins 4.
```

**Comment by traversaro** [comment]
> velocityControlImplementationType

Good catch. Let's delay the release then.

**Review by diegoferigo — APPROVED** [review]

**Review by Nicogene — APPROVED** [review]

**Comment by traversaro** [comment]
Blocked by  https://github.com/robotology/gazebo-yarp-plugins/issues/577 .

**Pull request merged**
