### PR TITLE
Fix for getDevicesAsPolyDriverList method used by libYARP_robotinterface

### PR DESCRIPTION
**Pull request by traversaro**
In particular, ensure that also devices registered by sensor plugins are correctly exposed to libYARP_robotinterface.

Fix https://github.com/robotology/gazebo-yarp-plugins/issues/543 .

cc @drdanz @randaz81

### CODE REVIEW

**Review by drdanz — APPROVED** [review]
LGTM, tested with ROS and ROS2 nws

**Comment by traversaro** [comment]
Actually `default` it just happens to be the world name, we should get the world name and use that instead of hardcoding `default::`, looking into it.

**Comment by traversaro** [comment]
@drdanz I updated the code to be generic w.r.t. to world name, could you check if this is still working for you? Thanks!

**Review by drdanz — COMMENTED** [review]
Tested again, it works, thanks

**Comment by traversaro** [comment]
Thanks @drdanz !

**Pull request merged**
