### PR TITLE
New docker images in Travis

### PR DESCRIPTION
**Pull request by diegoferigo**
The new [`robotology/robotology-tdd`](https://hub.docker.com/r/robotology/robotology-tdd/) image substitutes the `robotology/yarp-tdd` currently used by this project.

The pros of the new image are the following:

- Based on the robotology-superbuild: usually it provides a working repositories configuration
- Nightly builds instead of manually-triggered generation

Hopefully we'll run less often in misalignments due to outdated dependencies. 

cc @valegagge

### CODE REVIEW

**Comment by diegoferigo** [comment]
@traversaro I was still not able to debug the following error during the execution of `testrunner`:

```
Loading /projects/robotology-superbuild/robotology/icub-tests/suits/basics-icubGazeboSim.xml
[testrunner] Root tag of the xml file is the " suit " tag, that is deprecated since RTF 1.3, and will be removed in RTF 1.5 .
Starting test runner.
Test suite Basic Tests Suite started...
[INFO]  (Basic Tests Suite) reports: yarpmanager is setting up the fixture...
Test case FtSensorTest started...
[INFO]  (FtSensorTest) reports: Loading configuration from /projects/robotology-superbuild/robotology/icub-tests/suits/contexts/icubGazeboSim/test_ft_left_arm.ini
[INFO]  (Test FT sensors Left Arm) reports: connecting from /iCubTest/FTsensor to /icubSim/left_arm/analog:o

[ERROR] (Test FT sensors Left Arm) asserts error on (Network::connect(portname, port.getName())) with exception: could not connect to remote port /icubSim/left_arm/analog:o, FT sensor unavailable
Test case Test FT sensors Left Arm failed!
Test case FtSensorTest started...
[INFO]  (FtSensorTest) reports: Loading configuration from /projects/robotology-superbuild/robotology/icub-tests/suits/contexts/icubGazeboSim/test_ft_left_foot.ini
[INFO]  (Test FT sensors Left Foot) reports: connecting from /iCubTest/FTsensor to /icubSim/left_foot/analog:o

[ERROR] (Test FT sensors Left Foot) asserts error on (Network::connect(portname, port.getName())) with exception: could not connect to remote port /icubSim/left_foot/analog:o, FT sensor unavailable
Test case Test FT sensors Left Foot failed!
Test case FtSensorTest started...
[INFO]  (FtSensorTest) reports: Loading configuration from /projects/robotology-superbuild/robotology/icub-tests/suits/contexts/icubGazeboSim/test_ft_left_leg.ini
[INFO]  (Test FT sensors Left Leg) reports: connecting from /iCubTest/FTsensor to /icubSim/left_leg/analog:o

[ERROR] (Test FT sensors Left Leg) asserts error on (Network::connect(portname, port.getName())) with exception: could not connect to remote port /icubSim/left_leg/analog:o, FT sensor unavailable
Test case Test FT sensors Left Leg failed!
Test case FtSensorTest started...
[INFO]  (FtSensorTest) reports: Loading configuration from /projects/robotology-superbuild/robotology/icub-tests/suits/contexts/icubGazeboSim/test_ft_right_arm.ini
[INFO]  (Test FT sensors Right Arm) reports: connecting from /iCubTest/FTsensor to /icubSim/right_arm/analog:o

[ERROR] (Test FT sensors Right Arm) asserts error on (Network::connect(portname, port.getName())) with exception: could not connect to remote port /icubSim/right_arm/analog:o, FT sensor unavailable
Test case Test FT sensors Right Arm failed!
Test case FtSensorTest started...
[INFO]  (FtSensorTest) reports: Loading configuration from /projects/robotology-superbuild/robotology/icub-tests/suits/contexts/icubGazeboSim/test_ft_right_foot.ini
[INFO]  (Test FT sensors Right Foot) reports: connecting from /iCubTest/FTsensor to /icubSim/right_foot/analog:o

[ERROR] (Test FT sensors Right Foot) asserts error on (Network::connect(portname, port.getName())) with exception: could not connect to remote port /icubSim/right_foot/analog:o, FT sensor unavailable
Test case Test FT sensors Right Foot failed!
Test case FtSensorTest started...
[INFO]  (FtSensorTest) reports: Loading configuration from /projects/robotology-superbuild/robotology/icub-tests/suits/contexts/icubGazeboSim/test_ft_right_leg.ini
[INFO]  (Test FT sensors Right Leg) reports: connecting from /iCubTest/FTsensor to /icubSim/right_leg/analog:o

[ERROR] (Test FT sensors Right Leg) asserts error on (Network::connect(portname, port.getName())) with exception: could not connect to remote port /icubSim/right_leg/analog:o, FT sensor unavailable
Test case Test FT sensors Right Leg failed!
[INFO]  (Basic Tests Suite) reports: yarpmanager is tearing down the fixture...
Test suite Basic Tests Suite failed!
Ending test runner.

---------- results -----------
Total number of test suites  : 1
Number of passed test suites : 0
Number of failed test suites : 1
Total number of test cases   : 6
Number of passed test cases  : 0
Number of failed test cases  : 6
```

Any idea? I'm not a RTF expert.

**Comment by traversaro** [comment]
Actually that test ( https://github.com/robotology/icub-tests/tree/master/src/ftsensor-tests, called by https://github.com/robotology/icub-tests/blob/master/suits/basics-icubGazeboSim.xml#L13 ) is a bit flaky, because it does not wait for the FT sensor to be up before  running the test. It could be just that with the docker stuff we are not lucky.

**Comment by traversaro** [comment]
I  tried to increase the timeout in https://github.com/robotology/icub-tests/commit/1b9ecd07655dda15de897b7b8bab1947cd9a0b9b , but the proper solution is https://github.com/robotology/yarp/issues/1836 . 

It is also possible that the actual problem is that Gazebo is not starting correctly and RTF is not properly printing an error.

**Comment by traversaro** [comment]
Ah damn, to test https://github.com/robotology/icub-tests/commit/1b9ecd07655dda15de897b7b8bab1947cd9a0b9b we need to regenerate the images... : /

**Comment by traversaro** [comment]
@diegoferigo Any idea on how to launch a rebuild of the images from https://hub.docker.com/r/robotology/robotology-tdd/ ?

**Comment by diegoferigo** [comment]
@traversaro The images are built with a nightly Travis build. If you want to manually trigger a rebuild, you need to open the last Travis test of the docker_images repository and relaunch the last build (or commit something)

**Comment by traversaro** [comment]
@diegoferigo Cool.

**Comment by diegoferigo** [comment]
@traversaro Unfortunately the workaround in icub-tests is not enough, it didn't solve the error :/

**Comment by traversaro** [comment]
Then the problem is probably another (or the delay should be even longer). I am currently out of time to test that, so if no one volunteer some time to debug the issue I propose that we remove the RTF-based test so at least we can test the successful compilation of the plugins.

**Comment by diegoferigo** [comment]
Right now I have other more urgent priorities, I'd temporary disable RTF tests waiting for some more bandwidth.

**Comment by diegoferigo** [comment]
@traversaro Yes that's fine :+1:

**Comment by traversaro** [comment]
Thanks @diegoferigo .

**Pull request merged**
