### PR TITLE
External wrench smoothing feature for externalwrench gazebo yarp plugin

### PR DESCRIPTION
**Pull request by Yeshasvitvs**
This is a similar PR as https://github.com/robotology/gazebo-yarp-plugins/pull/430

It introduces the feature of smoothing the wrench when using externalwrench gazebo yarp plugin

### CODE REVIEW

**Comment by traversaro** [comment]
Can you make sure that all the commits corresponds to email associated to your GitHub account for the CLA? Thanks a lot!

**Comment by traversaro** [comment]
@prashanthr05 can you check if your review from https://github.com/robotology/gazebo-yarp-plugins/pull/430 has been addressed? Thanks!

**Comment by traversaro** [comment]
Can you update the changelog: https://github.com/robotology/gazebo-yarp-plugins/blob/devel/CHANGELOG.md ? Thanks!

**Comment by Yeshasvitvs** [comment]
> Can you make sure that all the commits corresponds to email associated to your GitHub account for the CLA? Thanks a lot!

I am trying to fix it. 
The problem seems to be due to the git config user.name I set which is as `Yeshasvi Tirupachuri` where as the original commits were done with user.name set as `Yeshasvitvs`

Any pointers to how to fix this ?

**Comment by traversaro** [comment]
I would rebase all the commits together, and then change the author with `git commit --amend --author`, see https://makandracards.com/makandra/1717-git-change-author-of-a-commit .

**Comment by Yeshasvitvs** [comment]
Given https://github.com/robotology/gazebo-yarp-plugins/pull/430#issuecomment-510032548 may be @GiulioRomualdi is also interested in reviewing this PR

**Comment by prashanthr05** [comment]
> @prashanthr05 can you check if your review from #430 has been addressed? Thanks!

Yes, it has been addressed. But in the previous review, I had not verified the math. However, it looks like the PR was tested and seems to have been working properly.

I will go through the link added as documentation and cross-verify if required. Please let me know.

**Comment by traversaro** [comment]
I think it is ok to approve the PR  @prashanthr05 even if you do not review the math in detail.

**Comment by Yeshasvitvs** [comment]
Some checks are failing due to https://github.com/robotology/robotology-superbuild/issues/420 which is addressed in https://github.com/robotology/gazebo-yarp-plugins/pull/496

**Comment by traversaro** [comment]
Hi @Yeshasvitvs , let me know if you prefer to curate the commits, or if it is ok that I merge with squash.

**Comment by Yeshasvitvs** [comment]
> if it is ok that I merge with squash.

Please go ahead

**Pull request merged**
