### PR TITLE
Fixed initialization of the local simulation time from Gazebo simTime on first call of onUpdate

### PR DESCRIPTION
**Pull request by nunoguedelha**
Fixes https://github.com/robotology/gazebo-yarp-plugins/issues/475.

Refer to the analysis in the respective issue.

### CODE REVIEW

**Comment by traversaro** [comment]
Thanks, can you add a reference to this PR in the Changelog? Thanks!

**Comment by traversaro** [comment]
The CI is failing due to https://github.com/actions/virtual-environments/issues/675, please ignore it, thanks.

**Comment by nunoguedelha** [comment]
Fix tested on top of commit https://github.com/robotology/gazebo-yarp-plugins/commit/d1eff470f2bbc63f4fd451b863494b29180e5849, which is more recent than the last commit https://github.com/robotology/gazebo-yarp-plugins/commit/283996437588c7cd0d6759094758c773437cf5c5 where the impacted file changed.

**Comment by nunoguedelha** [comment]
> Thanks, can you add a reference to this PR in the Changelog? Thanks!

on it...

**Comment by nunoguedelha** [comment]
Ciao @traversaro , is anything else missing before you can approve?

**Comment by traversaro** [comment]
> 
> 
> Ciao @traversaro , is anything else missing before you can approve?

Nothing is missing, we can merge. Just to explain why this was stack: I don't have notifications for new commit in the PR, so unless someone comments in the PR I have no way to know if the review comments have been addressed.

**Pull request merged**
