### PR TITLE
update worldinterface::makeBox

### PR DESCRIPTION
**Pull request by valegagge**
worldinterface plugin: now the makeBox function doesn't append number at the end of given name of box.

please see https://github.com/robotology/gazebo-yarp-plugins/issues/402

### CODE REVIEW

**Comment by valegagge** [comment]
@traversaro also makeFrame, right?

**Comment by traversaro** [comment]
Indeed, I missed that!

**Comment by valegagge** [comment]
Done!

**Comment by traversaro** [comment]
Ok for me, but let's wait for @randaz81 opinion given that is the one more involved in this.

**Comment by traversaro** [comment]
I just saw that @randaz81 is away till the 4th of December. If you think he will not have any problem with this, I think we can merge.

**Comment by valegagge** [comment]
I'm not used to work with gazebo and in particular with worldinterface plugin. 
I think the current behaviour of mentioned functions doesn't seem usefull.
I prefer tomerge and in case of issue we can restore the current behaviour, but , since this pr is not blocking for me, I can wait @randaz

**Comment by traversaro** [comment]
friendly ping @randaz81

**Comment by randaz81** [comment]
@valegagge it seems ok to me, but can you please do this additional check?
What happens if a user tries to create an object with the same name of an object that already exists? Previously, a number was appended, resulting in a different name. Now I think that two objects with the same name are created. Maybe this action should be prevented an error message displayed?

**Comment by valegagge** [comment]
@randaz81 
>  it seems ok to me, but can you please do this additional check?

Done! please see [this commit](https://github.com/robotology/gazebo-yarp-plugins/pull/404/commits/5ccd19d74eb5442df0a99dc3427a1a773d36d685)

About the error message displayed, I used the existing error management: prints yError << "error_string" and returns an empty string. This means that on error the response of rpc command is nothing and only on logger there is the error or on bash where gazebo is running.

**Pull request merged**
