### PR TITLE
Update coupling parameters for thumb and pinkie of Hand Mk4

### PR DESCRIPTION
**Pull request by mfussi66**
This PR aims to change the parameters used to compute the coupling law between the degree of actuation and the finger joints of thumb and pinkie of the new Mk4 hand.
The measurements are taken directly from the CAD models.

Here is a video of the result:

https://user-images.githubusercontent.com/38140169/163136337-217b62d2-8611-4147-be59-5dec5ce693b9.mp4

### CODE REVIEW

**Comment by mfussi66** [comment]
cc @pattacini @traversaro

**Comment by traversaro** [comment]
Thanks! Can you add a line on the changelog? Thanks.

**Comment by mfussi66** [comment]
Done! @traversaro

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks!

**Pull request merged**
