### PR TITLE
Cleanup for YARP 3 

### PR DESCRIPTION
**Pull request by traversaro**

### CODE REVIEW

**Comment by traversaro** [comment]
Can you bump the version number in https://github.com/robotology/gazebo-yarp-plugins/blob/devel/CMakeLists.txt#L20 ?

**Comment by traversaro** [comment]
@diegoferigo Any idea on how to handle Travis? With the old docker-less structure, we just had to change the branch of YARP used to compile it from source, now I guess new docker images would need to be uploaded to dockerhub.

**Comment by traversaro** [comment]
While waiting for the Travis fix, I think we can merge it nevertheless, otherwise the `devel` branch is effectively useless.

**Comment by jeljaik** [comment]
@traversaro changed required YARP version in bac74db51bd65189ee56f30939a65f77ba0fc96d

**Comment by diegoferigo** [comment]
> Any idea on how to handle Travis?

@traversaro Yes I triggered a rebuild. I have planned a task to handle better the images but it does not have top priority right now.

**Comment by traversaro** [comment]
Thanks

**Comment by diegoferigo** [comment]
Right now only @drdanz and me are part of the organization on dockerhub, make an account and send me the email, I can add you.

**Comment by traversaro** [comment]
@diegoferigo https://hub.docker.com/u/traversaro/ Thanks!

**Comment by diegoferigo** [comment]
@traversaro Done!

**Pull request merged**
